# Generated by Django 6.0.5 on 2026-06-01 11:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mario_maker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='1', max_length=20)),
                ('hash_pswrd', models.CharField(default='2', max_length=255)),
                ('follows', models.ManyToManyField(to='mario_maker.user')),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.IntegerField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='3', max_length=255)),
                ('json', models.JSONField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mario_maker.user')),
            ],
        ),
        migrations.DeleteModel(
            name='Player',
        ),
    ]
