# Generated by Django 6.0.5 on 2026-06-03 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mario_maker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='creation_date',
        ),
        migrations.AddField(
            model_name='level',
            name='creation_date',
            field=models.DateField(auto_now=True),
        ),
    ]
