# Generated by Django 6.0.5 on 2026-06-08 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mario_maker', '0002_remove_player_creation_date_level_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='creation_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
