# Generated by Django 6.0.5 on 2026-06-09 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mario_maker', '0003_alter_level_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='id',
            field=models.IntegerField(default=int, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='player',
            name='id',
            field=models.IntegerField(default=int, editable=False, primary_key=True, serialize=False),
        ),
    ]
