# Generated by Django 6.0.5 on 2026-06-09 09:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mario_maker', '0004_alter_level_id_alter_player_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='player',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
