# Generated by Django 6.0.5 on 2026-06-09 13:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mario_maker', '0005_alter_level_id_alter_player_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
    ]
