# Generated by Django 6.0.5 on 2026-06-02 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mario_maker', '0005_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(default=int, editable=False, primary_key=True, serialize=False),
        ),
    ]
