# Generated by Django 6.0.5 on 2026-06-02 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mario_maker', '0007_alter_level_id_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='follows',
            field=models.ManyToManyField(null=True, related_name='user_follows', to='mario_maker.user'),
        ),
    ]
