# Generated by Django 6.0.5 on 2026-06-02 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mario_maker', '0008_alter_user_follows'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default='1', max_length=20, unique=True),
        ),
    ]
